CREATE DATABASE CLINIC TEMPLATE template0;
CREATE USER admin WITH ENCRYPTED PASSWORD '123';
GRANT ALL PRIVILEGES ON DATABASE CLINIC TO admin;


create table clinic(
ID INT,
CLINIC_NAME VARCHAR(25),
primary key(ID)
);

create table DOCTOR(
ID INT,
DOCTOR_NAME VARCHAR(25),
SPECIALITY VARCHAR(25),
FEES int,
primary key(ID)
);

CREATE TABLE SCHEDULE(
    ID INT,
    CLINIC_ID INT,
    DOCTOR_ID INT,
    FOREIGN KEY(Doctor_ID) REFERENCES DOCTOR(ID),
    FOREIGN KEY(CLINIC_ID) REFERENCES CLINIC(ID),
    PRIMARY KEY (ID)
);

create table USERS(
ID INT,
NAME VARCHAR(25),
USER_NAME VARCHAR(25),
password VARCHAR(25),
primary key(ID)
);

create table APPOINTMENT(
ID INT,
USER_ID INT,
Doctor_ID INT,
CLINIC_ID INT,
FOREIGN KEY(USER_ID) REFERENCES USERS(ID),
FOREIGN KEY(Doctor_ID) REFERENCES DOCTOR(ID),
FOREIGN KEY(CLINIC_ID) REFERENCES CLINIC(ID),
primary key(ID)
);

insert into CLINIC values
(1,'CLINIC1'),
(2,'CLINIC2'),
(3,'CLINIC3'),
(4,'CLINIC4'),
(5,'CLINIC5');

insert into DOCTOR values
(1,'DR1','PED',3000),
(2,'DR2','ENT',2000),
(3,'DR3','PHYSIO',5000),
(4,'DR4','GENERAL',2000),
(5,'DR5','ORTHO',6000);

insert into SCHEDULE values
(1,1,1),
(2,1,2),
(3,1,3),
(4,2,4),
(5,2,2),
(6,3,3),
(7,4,1),
(8,4,2),
(9,5,1),
(10,5,5),
(11,5,3);


